# Generated by Django 6.0.6 on 2026-07-08 06:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationmembership_organization_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationMembership',
            new_name='OrganizationMember',
        ),
    ]
