# Generated by Django 6.0.6 on 2026-07-11 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizationmember_alter_organization_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_member'),
        ),
        migrations.AlterModelTable(
            name='organizationmember',
            table='organization_member',
        ),
    ]
