# Generated by Django 6.0.6 on 2026-07-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(help_text='The department this project belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='department.department'),
        ),
    ]
