# Generated by Django 6.0.6 on 2026-06-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments_comment',
        ),
    ]
