# Generated by Django 6.0.6 on 2026-07-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PM', 'Project Manager'), ('TM', 'Team Member')], default='TM', max_length=15),
        ),
    ]
