# Generated by Django 6.0.6 on 2026-07-13 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_initial'),
        ('organization', '0004_alter_organizationmember_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_department'),
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
